# theme: minima # Very Minimal
# remote_theme: chrisrhymes/mere-blog-theme # Not displaying posts
remote_theme: samarsault/texture
texture:
  title: "Giovanni's Blog"
  tagline: My Blog
  author: Giovanni Santini
  date_format: "%b %-d, %Y"
  style: green
  showNav: true

  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman # format: locale/username
